[2022-07-12 22:44:34,993] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 22:44:35,010] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 22:44:35,010] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 22:44:35,011] {taskinstance.py:1239} INFO - Starting attempt 38 of 39
[2022-07-12 22:44:35,011] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 22:44:35,025] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-11 00:00:00+00:00
[2022-07-12 22:44:35,032] {standard_task_runner.py:52} INFO - Started process 163 to run task
[2022-07-12 22:44:35,037] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_project_dag-12', 'download_dataset_task', 'scheduled__2022-07-11T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_gcs.py', '--cfg-path', '/tmp/tmptw10pjq0', '--error-file', '/tmp/tmpp9j_e74n']
[2022-07-12 22:44:35,038] {standard_task_runner.py:77} INFO - Job 105: Subtask download_dataset_task
[2022-07-12 22:44:35,124] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_project_dag-12.download_dataset_task scheduled__2022-07-11T00:00:00+00:00 [running]> on host 71caeb0e3cbd
[2022-07-12 22:44:35,197] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_project_dag-12
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-11T00:00:00+00:00
[2022-07-12 22:44:35,198] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-12 22:44:35,199] {subprocess.py:74} INFO - Running command: ['bash', '-c', '#!/usr/bin\npip install kaggle\n\nexport KAGGLE_USERNAME=yusufkamorudeen\nexport KAGGLE_KEY=f9e7d64641f620123ab335c78451fdf4\n\n\n\n\n\ndataset_id=mashlyn\ndata_name=online-retail-ii-uci\n\nkaggle datasets download -d $dataset_id/$data_name --unzip -p "/opt/***/$dataset_id/$dataset_name"\n\n\n\n\n\n#mv $data_name uk_housing.zip\n\n\n']
[2022-07-12 22:44:35,215] {subprocess.py:85} INFO - Output:
[2022-07-12 22:44:36,821] {subprocess.py:89} INFO - Defaulting to user installation because normal site-packages is not writeable
[2022-07-12 22:44:37,276] {subprocess.py:89} INFO - Collecting kaggle
[2022-07-12 22:44:37,383] {subprocess.py:89} INFO -   Downloading kaggle-1.5.12.tar.gz (58 kB)
[2022-07-12 22:44:37,443] {subprocess.py:89} INFO -   Preparing metadata (setup.py): started
[2022-07-12 22:44:38,073] {subprocess.py:89} INFO -   Preparing metadata (setup.py): finished with status 'done'
[2022-07-12 22:44:38,099] {subprocess.py:89} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.16.0)
[2022-07-12 22:44:38,100] {subprocess.py:89} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2020.12.5)
[2022-07-12 22:44:38,100] {subprocess.py:89} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.8.2)
[2022-07-12 22:44:38,101] {subprocess.py:89} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.7/site-packages (from kaggle) (2.26.0)
[2022-07-12 22:44:38,283] {subprocess.py:89} INFO - Collecting tqdm
[2022-07-12 22:44:38,304] {subprocess.py:89} INFO -   Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
[2022-07-12 22:44:38,318] {subprocess.py:89} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.7/site-packages (from kaggle) (4.0.1)
[2022-07-12 22:44:38,318] {subprocess.py:89} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.7/site-packages (from kaggle) (1.26.7)
[2022-07-12 22:44:38,328] {subprocess.py:89} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.7/site-packages (from python-slugify->kaggle) (1.3)
[2022-07-12 22:44:38,348] {subprocess.py:89} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (3.3)
[2022-07-12 22:44:38,351] {subprocess.py:89} INFO - Requirement already satisfied: charset-normalizer~=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from requests->kaggle) (2.0.9)
[2022-07-12 22:44:38,392] {subprocess.py:89} INFO - Building wheels for collected packages: kaggle
[2022-07-12 22:44:38,393] {subprocess.py:89} INFO -   Building wheel for kaggle (setup.py): started
[2022-07-12 22:44:39,262] {subprocess.py:89} INFO -   Building wheel for kaggle (setup.py): finished with status 'done'
[2022-07-12 22:44:39,263] {subprocess.py:89} INFO -   Created wheel for kaggle: filename=kaggle-1.5.12-py3-none-any.whl size=73051 sha256=29889b090c2e324fde2222b5d4c29cf2b0e2d15f4afb09bc4f7ffffb48b8fb65
[2022-07-12 22:44:39,263] {subprocess.py:89} INFO -   Stored in directory: /home/***/.cache/pip/wheels/62/d6/58/5853130f941e75b2177d281eb7e44b4a98ed46dd155f556dc5
[2022-07-12 22:44:39,266] {subprocess.py:89} INFO - Successfully built kaggle
[2022-07-12 22:44:46,241] {subprocess.py:89} INFO - Installing collected packages: tqdm, kaggle
[2022-07-12 22:44:46,506] {subprocess.py:89} INFO - Successfully installed kaggle-1.5.12 tqdm-4.64.0
[2022-07-12 22:44:46,745] {subprocess.py:89} INFO - WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
[2022-07-12 22:44:46,746] {subprocess.py:89} INFO - You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[2022-07-12 22:44:48,132] {subprocess.py:89} INFO - Downloading online-retail-ii-uci.zip to /opt/***/mashlyn
[2022-07-12 22:44:50,077] {subprocess.py:89} INFO -   0%|          | 0.00/14.5M [00:00<?, ?B/s] 14%|█▍        | 2.00M/14.5M [00:00<00:00, 13.8MB/s] 28%|██▊       | 4.00M/14.5M [00:00<00:00, 14.2MB/s] 41%|████▏     | 6.00M/14.5M [00:00<00:00, 15.2MB/s] 55%|█████▌    | 8.00M/14.5M [00:00<00:00, 16.0MB/s] 69%|██████▉   | 10.0M/14.5M [00:00<00:00, 16.4MB/s] 83%|████████▎ | 12.0M/14.5M [00:01<00:00, 9.56MB/s] 96%|█████████▋| 14.0M/14.5M [00:01<00:00, 11.2MB/s]100%|██████████| 14.5M/14.5M [00:01<00:00, 12.6MB/s]
[2022-07-12 22:44:50,078] {subprocess.py:89} INFO - 
[2022-07-12 22:44:50,228] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-12 22:44:50,276] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_project_dag-12, task_id=download_dataset_task, execution_date=20220711T000000, start_date=20220712T224434, end_date=20220712T224450
[2022-07-12 22:44:50,328] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-12 22:44:50,389] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
